version: "3.7"

services:
  node:
    build:
      context: .
      target: ${NODE_ENV}
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./server/public/files:./server/public/files
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
