name: Unit Tests

on:
  push:
    branches:
      [main]
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          sudo npm install 
          sudo npm run migrate
          sudo npm test
