name: Unit Tests

on:
  push:
    branches:
      [main]
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make gradlew executable
        run: chmod +x -R /server
      - name: Run Tests
        run: |
          npm install 
          npm run migrate
          npm test
